RUS_CHARS = [
    'А'.encode('utf-8'),
    'Б'.encode('utf-8'),
    'В'.encode('utf-8'),
    'Г'.encode('utf-8'),
    'Д'.encode('utf-8'),
    'Е'.encode('utf-8'),
    'Ж'.encode('utf-8'),
    'З'.encode('utf-8'),
    'И'.encode('utf-8'),
    'Й'.encode('utf-8'),
    'К'.encode('utf-8'),
    'Л'.encode('utf-8'),
    'М'.encode('utf-8'),
    'Н'.encode('utf-8'),
    'О'.encode('utf-8'),
    'П'.encode('utf-8'),
    'Р'.encode('utf-8'),
    'С'.encode('utf-8'),
    'Т'.encode('utf-8'),
    'У'.encode('utf-8'),
    'Ф'.encode('utf-8'),
    'Х'.encode('utf-8'),
    'Ц'.encode('utf-8'),
    'Ч'.encode('utf-8'),
    'Ш'.encode('utf-8'),
    'Щ'.encode('utf-8'),
    'Ъ'.encode('utf-8'),
    'Ы'.encode('utf-8'),
    'Ь'.encode('utf-8'),
    'Э'.encode('utf-8'),
    'Ю'.encode('utf-8'),
    'Я'.encode('utf-8'),
    'Ё'.encode('utf-8'),
    'а'.encode('utf-8'),
    'б'.encode('utf-8'),
    'в'.encode('utf-8'),
    'г'.encode('utf-8'),
    'д'.encode('utf-8'),
    'е'.encode('utf-8'),
    'ж'.encode('utf-8'),
    'з'.encode('utf-8'),
    'и'.encode('utf-8'),
    'й'.encode('utf-8'),
    'к'.encode('utf-8'),
    'л'.encode('utf-8'),
    'м'.encode('utf-8'),
    'н'.encode('utf-8'),
    'о'.encode('utf-8'),
    'п'.encode('utf-8'),
    'р'.encode('utf-8'),
    'с'.encode('utf-8'),
    'т'.encode('utf-8'),
    'у'.encode('utf-8'),
    'ф'.encode('utf-8'),
    'х'.encode('utf-8'),
    'ц'.encode('utf-8'),
    'ч'.encode('utf-8'),
    'ш'.encode('utf-8'),
    'щ'.encode('utf-8'),
    'ъ'.encode('utf-8'),
    'ы'.encode('utf-8'),
    'ь'.encode('utf-8'),
    'э'.encode('utf-8'),
    'ю'.encode('utf-8'),
    'я'.encode('utf-8'),
    'ё'.encode('utf-8'),
]

# путь к рабочей директории
P_DIR_PATH = '/home/andrew/Recognizerka/'

# размер русского алфавита
ALPHABET_SIZE = 33